// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using receptek_backend.Models;

#nullable disable

namespace receptek_backend.Migrations
{
    [DbContext(typeof(ReceptContext))]
    partial class ReceptContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("receptek_backend.Models.Kategoriak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nev")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nev");

                    b.HasKey("Id")
                        .HasName("PK__kategori__3213E83F6968877E");

                    b.ToTable("kategoriak", (string)null);
                });

            modelBuilder.Entity("receptek_backend.Models.Receptek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("KatId")
                        .HasColumnType("int")
                        .HasColumnName("kat_id");

                    b.Property<string>("KepEleresiUt")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("kep_eleresi_ut");

                    b.Property<string>("Leiras")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("leiras");

                    b.Property<string>("Nev")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nev");

                    b.HasKey("Id")
                        .HasName("PK__receptek__3213E83FB8ED4774");

                    b.HasIndex("KatId");

                    b.ToTable("receptek", (string)null);
                });

            modelBuilder.Entity("receptek_backend.Models.Receptek", b =>
                {
                    b.HasOne("receptek_backend.Models.Kategoriak", "Kat")
                        .WithMany("Recepteks")
                        .HasForeignKey("KatId")
                        .HasConstraintName("FK__receptek__leiras__29572725");

                    b.Navigation("Kat");
                });

            modelBuilder.Entity("receptek_backend.Models.Kategoriak", b =>
                {
                    b.Navigation("Recepteks");
                });
#pragma warning restore 612, 618
        }
    }
}
